# Generated by Django 6.1.2 on 2026-10-07 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('round_1', 'Round 1'), ('round_2', 'Round 2'), ('final', 'Final'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_1_time_ms', models.PositiveBigIntegerField(default=0)),
                ('round_2_time_ms', models.PositiveBigIntegerField(default=0)),
                ('total_time_ms', models.PositiveBigIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('total_hints_used', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField()),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to='game.gamesession')),
            ],
            options={
                'ordering': ['total_time_ms', 'total_attempts', 'total_hints_used', 'completed_at'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation_version', models.CharField(default='v1', max_length=30)),
                ('secret_data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle', to='game.gamesession')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('participant_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=200)),
                ('game_mode', models.CharField(choices=[('single', 'Single Player'), ('team', 'Team Mode')], max_length=10)),
                ('team_name', models.CharField(blank=True, max_length=120)),
                ('team_leader_name', models.CharField(blank=True, max_length=120)),
                ('event_year', models.PositiveIntegerField(default=2026)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event_year', 'email'), name='unique_registration_per_event_email')],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to='game.registration'),
        ),
        migrations.CreateModel(
            name='RoundState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveSmallIntegerField(choices=[(1, 'Round 1'), (2, 'Round 2')])),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('solved', 'Solved')], default='locked', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_states', to='game.gamesession')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='HintUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hint_code', models.CharField(max_length=50)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('round_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_usages', to='game.roundstate')),
            ],
            options={
                'ordering': ['used_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('stage_1', 'Stage 1'), ('stage_2', 'Stage 2')], max_length=10)),
                ('selected_nodes', models.JSONField(default=list)),
                ('selected_order', models.JSONField(default=list)),
                ('correctly_placed', models.PositiveSmallIntegerField(default=0)),
                ('incorrectly_placed', models.PositiveSmallIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('round_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='game.roundstate')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='roundstate',
            constraint=models.UniqueConstraint(fields=('game_session', 'round_number'), name='unique_round_per_session'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['round_state', 'stage'], name='attempt_round_stage_idx'),
        ),
    ]
