# Generated by Django 6.1.2 on 2026-10-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzleinstance',
            name='public_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='puzzleinstance',
            name='secret_data',
            field=models.JSONField(default=dict),
        ),
    ]
