# Generated by Django 6.1.2 on 2026-10-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_puzzleinstance_public_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hintusage',
            options={},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='college',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='game_mode',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='team_leader_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='team_name',
        ),
        migrations.AddField(
            model_name='registration',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='stage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='roundstate',
            name='status',
            field=models.CharField(default='locked', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('event_year', 'google_sub'), name='unique_google_registration_per_event'),
        ),
    ]
