# Generated by Django 6.1.2 on 2026-10-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_hintusage_options_remove_registration_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='google_sub',
            field=models.CharField(db_index=True, default='migration-placeholder', max_length=255),
            preserve_default=False,
        ),
    ]
